//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;

namespace SuperBoyView.SuperBoyControl {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="SuperBoyControl.ISuperBoyICloud")]
    public interface ISuperBoyICloud {
        
        [OperationContract(Action="http://tempuri.org/ISuperBoyICloud/SuperBoyCloud", ReplyAction="http://tempuri.org/ISuperBoyICloud/SuperBoyCloudResponse")]
        string SuperBoyCloud(string CloudJson);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface ISuperBoyICloudChannel : ISuperBoyICloud, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class SuperBoyICloudClient : ClientBase<ISuperBoyICloud>, ISuperBoyICloud {
        
        public SuperBoyICloudClient() {
        }
        
        public SuperBoyICloudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuperBoyICloudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperBoyICloudClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperBoyICloudClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SuperBoyCloud(string CloudJson) {
            return base.Channel.SuperBoyCloud(CloudJson);
        }
    }
}
