//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperBoyView.SuperBoyControl {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SuperBoyControl.ISuperBoyICloud")]
    public interface ISuperBoyICloud {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperBoyICloud/SuperBoyC", ReplyAction="http://tempuri.org/ISuperBoyICloud/SuperBoyCResponse")]
        string SuperBoyC();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISuperBoyICloudChannel : SuperBoyView.SuperBoyControl.ISuperBoyICloud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuperBoyICloudClient : System.ServiceModel.ClientBase<SuperBoyView.SuperBoyControl.ISuperBoyICloud>, SuperBoyView.SuperBoyControl.ISuperBoyICloud {
        
        public SuperBoyICloudClient() {
        }
        
        public SuperBoyICloudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuperBoyICloudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperBoyICloudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperBoyICloudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SuperBoyC() {
            return base.Channel.SuperBoyC();
        }
    }
}
